config/routes.rb
Talentedio::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :password_resets, path: 'passwords'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'settings' => 'users#edit'
  put 'settings' => 'users#update'
  delete 'account/delete' => 'users#destroy', :as => 'delete_account'

  resource :profile, only: [:show, :edit, :update]
  resources :jobs

  root :to => 'main#home'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                              :integer          not null, primary key
#  email                           :string(255)      not null
#  crypted_password                :string(255)
#  salt                            :string(255)
#  created_at                      :datetime         not null
#  updated_at                      :datetime         not null
#  remember_me_token               :string(255)
#  remember_me_token_expires_at    :datetime
#  reset_password_token            :string(255)
#  reset_password_token_expires_at :datetime
#  reset_password_email_sent_at    :datetime
#  last_login_at                   :datetime
#  last_logout_at                  :datetime
#  last_activity_at                :datetime
#  last_login_from_ip_address      :string(255)
#  profile_id                      :integer
#  profile_type                    :string(255)
#  firstname                       :string(255)
#  lastname                        :string(255)
#

class User < ActiveRecord::Base
  authenticates_with_sorcery!

  belongs_to :profile, polymorphic: true

  attr_accessible :email, :password, :password_confirmation, :firstname, :lastname

  validates :firstname, presence: true
  validates :password, confirmation: true, length: { minimum: 6 }, allow_blank: true
  validates_presence_of :password, :on => :create
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: {with: VALID_EMAIL_REGEX}

  def developer?
    profile.class.name == "Developer"
  end

  def employer?
    profile.class.name == "Employer"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :require_login, :only => [:new, :create]
  before_filter :correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
  end

  def new
    @developer = User.new
    @employer = User.new
  end

  def create
    if params[:type] == 'developer'
      create_developer
    elsif params[:type] == 'employer'
      create_employer
    else
      redirect_to signup_path, alert: "Currently we don't support the user type at the moment."
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(params[:user])
      flash[:success] = "User was successfully updated."
      redirect_to settings_path
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path, notice: 'You have deleted your account, bye!'
  end

  private

  def correct_user
    @user ||= current_user
  end

  def create_developer
    @developer = User.new(params[:user])
    @employer = User.new
    if @developer.save
      profile = Developer.new
      profile.save(validate: false)
      @developer.update_attribute(:profile, profile)
      user_params = params[:user]
      login(user_params[:email],user_params[:password],true)
      flash[:success] = 'Registration successful.'
      redirect_to profile_path
    else
      render :new
    end
  end

  def create_employer
    @employer = User.new(params[:user])
    @developer = User.new
    if @employer.save
      profile = Employer.new
      profile.save(validate: false)
      @employer.update_attribute(:profile, profile)
      user_params = params[:user]
      login(user_params[:email],user_params[:password],true)
      flash[:success] = 'Registration successful.'
      redirect_to profile_path
    else
      render :new
    end
  end
end

app/views/users/_form_inputs.html.erb
<div class="form-inputs">
  <div class="row">
    <div class="large-6 columns">
      <%= f.input :firstname, label: "First name", :autofocus => true %>
    </div>
    <div class="large-6 columns">
      <%= f.input :lastname, label: "Last name" %>
    </div>
  </div>
  <%= f.input :email, :required => true %>
  <%= f.input :password, :required => true %>
  <%= f.input :password_confirmation, :required => true %>
</div>

app/views/users/edit.html.erb
<div class="row auth">
  <div class="large-6 large-centered columns">
    <h1 class="header">My account</h1>

    <div class="panel">
      <%= simple_form_for(@user, :url => settings_path, html: {class:"custom", :method => :put}) do |f| %>
        <%= render 'form_inputs', f: f %>
        <hr>
        <div class="form-actions">
          <%= f.button :submit, "Update" %>
        </div>
      <% end %>
    </div>
    <div class="other_info">
      <%= link_to "Cancel my account", delete_account_path, :data => { :confirm => "Are you sure?" }, :method => :delete %>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<div class="row auth">
  <div class="large-6 large-centered columns">
    <h1 class="header">Sign up</h1>

    <ul class="nav nav-tabs button-group round even-2" id="sign_up_type">
      <li class="<%= 'active' unless params[:type]=='employer' %>"><a href="#developer" class="button secondary" data-toggle="tab">I’m a developer</a></li>
      <li class="<%= 'active' if params[:type]=='employer' %>"><a href="#employer" class="button secondary" data-toggle="tab">I’m looking to hire</a></li>
    </ul>

    <div class="tab-content panel">
      <div class="tab-pane fade <%= 'active in' unless params[:type]=='employer' %>" id="developer">
        <%= simple_form_for(@developer, :url => signup_path(type: 'developer')) do |f| %>
          <div class="form-inputs">
            <div class="row">
              <div class="large-6 columns">
                <%= f.input :firstname, label: "First name", :autofocus => true %>
              </div>
              <div class="large-6 columns">
                <%= f.input :lastname, label: "Last name" %>
              </div>
            </div>
            <%= f.input :email, :required => true %>
            <%= f.input :password, :required => true %>
            <%= f.input :password_confirmation, :required => true %>
          </div>
          <hr>
          <div class="form-actions">
            <%= f.button :submit, "Sign up", class: "submit" %>
          </div>
        <% end %>
      </div>
      <div class="tab-pane fade <%= 'active in' if params[:type]=='employer' %>" id="employer">
        <%= simple_form_for(@employer, :url => signup_path(type: 'employer')) do |f| %>

          <div class="form-inputs">
            <div class="row">
              <div class="large-6 columns">
                <%= f.input :firstname, label: "First name", :autofocus => true %>
              </div>
              <div class="large-6 columns">
                <%= f.input :lastname, label: "Last name" %>
              </div>
            </div>
            <%= f.input :email, :required => true %>
            <%= f.input :password, :required => true %>
            <%= f.input :password_confirmation, :required => true %>
          </div>
          <%= hidden_field_tag :user_type, "employer" %>
          <hr>
          <div class="form-actions">
            <%= f.button :submit, "Sign up", class: "submit" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="other_info">
      <%= link_to "Sign in", login_path %>
    </div>
  </div>
</div>