config/routes.rb
Talentedio::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :password_resets, path: 'passwords'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'settings' => 'users#edit'
  put 'settings' => 'users#update'
  delete 'account/delete' => 'users#destroy', :as => 'delete_account'

  resource :profile, only: [:show, :edit, :update]
  resources :jobs

  root :to => 'main#home'
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :profile

  def show
    redirect_to edit_profile_path unless @profile.valid?
  end

  def edit

  end

  def update
    if @profile.update_attributes(params[:profile])
      flash[:success] = "Profile was successfully updated."
      redirect_to profile_path
    else
      render :edit
    end
  end

  private

  def profile
    @profile ||= current_user.profile
  end
end

app/views/profiles/show/_developer.html.erb
<h1>Show Developer</h1>

<%= @profile.location %>
<%= @profile.relocate %>
<%= @profile.position %>

app/views/profiles/show/_employer.html.erb
<h1>Show Company</h1>

<div>
  <%= @profile.company_name %>
  <%= auto_link @profile.website %>
</div>

<%- @profile.jobs.each do |job| -%>
<div>
  <%= job.title %>
  <%= link_to "edit", edit_job_path(job) %>
  <%= link_to "delete", job_path(job), method: :delete, conform: "Are you sure?" %>
</div>
<%- end -%>
<div>
  <%= link_to "New Job Posting", new_job_path, class: "button button-primary" %>
</div>