config/routes.rb
Talentedio::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :password_resets, path: 'passwords'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'settings' => 'users#edit'
  put 'settings' => 'users#update'
  delete 'account/delete' => 'users#destroy', :as => 'delete_account'

  resource :profile, only: [:show, :edit, :update]
  resources :jobs

  root :to => 'main#home'
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, :except => [:destroy]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:session][:email],params[:session][:password],params[:session][:remember])
      flash[:success] = 'Login successful.'
      redirect_back_or_to profile_path
    else
      flash.now[:alert] = "Wrong email or password."
      render :new
    end
  end

  def destroy
    logout
    flash[:success] = 'Logged out!'
    redirect_to root_path
  end
end

app/views/user_sessions/new.html.erb
<div class="row auth">
  <div class="large-6 large-centered columns">
    <h1 class="header">Sign in</h1>

    <div class="panel">
      <%= simple_form_for(:session, :url => login_path, html: {class:"custom", method: :post}) do |f| %>
        <div class="form-inputs">
          <%= f.input :email, :required => false, :autofocus => true %>
          <%= f.input :password, :required => false %>
          <%= f.input :remember, :as => :boolean, wrapper_html: {class: "inline-block"} %>
          <div class="other_info inline-block right">
            <%= link_to "Forgot your password?", new_password_reset_path %>
          </div>
        </div>
        <hr>
        <div class="form-actions">
          <%= f.button :submit, "Sign in", class: "submit" %>
        </div>
      <% end %>
    </div>
    <div class="other_info">
      <%= link_to "Sign up", signup_path %>
    </div>
  </div>
</div>