config/routes.rb
Talentedio::Application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :password_resets, path: 'passwords'

  get 'login' => 'user_sessions#new'
  post 'login' => 'user_sessions#create'
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  get 'signup' => 'users#new'
  post 'signup' => 'users#create'
  get 'settings' => 'users#edit'
  put 'settings' => 'users#update'
  delete 'account/delete' => 'users#destroy', :as => 'delete_account'

  resource :profile, only: [:show, :edit, :update]
  resources :jobs

  root :to => 'main#home'
end

app/views/layouts/_header.html.erb
<nav class="top-bar">
  <ul class="title-area">
    <!-- Title Area -->
    <li class="name">
      <h1><%= link_to "TALENTED", root_path %></h1>
    </li>
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <ul class="right">
      <%- if current_user -%>
        <li class="divider"></li>
        <li><%= link_to 'See profile', profile_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Edit Profile', edit_profile_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Setting', settings_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Sign out', logout_path, :method => :delete %></li>
      <%- else -%>
        <li class="divider"></li>
        <li><%= link_to "Sign in", login_path %></li>
        <li class="divider"></li>
        <li><%= link_to "Sign up", signup_path %></li>
      <%- end -%>
    </ul>
  </section>
</nav>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="large-12 columns">
    <%- flash.each do |name, msg| -%>
      <div data-alert class="alert-box <%= name %>">
        <%= msg %>
        <a href="#" class="close">×</a>
      </div>
    <%- end -%>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />
  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->
  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
  	<title><%= content_for?(:title) ? yield(:title) : "Talented - Your developer match maker." %></title>
  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= javascript_include_tag "application" %>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <script type="text/javascript" src="//use.typekit.net/nye8wqg.js"></script>
    <script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'layouts/header' %>
    <div class="row">
      <div class="large-12 columns">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>
  </body>
</html>